### ISSUE TITLE
Error with lein uberjar

### ISSUE THREAD

**Issue by Eschon** [hoebat/hara#6]
I recently included hara.io.scheduler in one of my projects. Now the compiled uberjar of my project doesn't work anymore.

This is easily reproducible with just hara.io.scheduler alone. I just created a new project witht `lein new app hara-test`. Then I added hara.io.scheduler to the project.clj and included the code from the walkthrough docs in the core.clj.

Using `lein run` everything works fine but when I run `lein uberjar` and then try to run the project with `java -jar hara-test.war` I get the following error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.Util.loadWithClass(Util.java:251)
	at hara_test.core.<clinit>(Unknown Source)
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'hara.state/empty
	at clojure.lang.Var$Unbound.throwArity(Var.java:45)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at hara.state.ova.Ova._set_state(ova.clj:107)
	at hara.state.base.common$set.invokeStatic(common.clj:90)
	at hara.state.base.common$set.invoke(common.clj:81)
	at hara.state.base.common$set.invokeStatic(common.clj:88)
	at hara.state.base.common$set.invoke(common.clj:81)
	at hara.state.ova$ova$fn__1838.invoke(ova.clj:207)
	at clojure.lang.AFn.call(AFn.java:18)
	at clojure.lang.LockingTransaction.run(LockingTransaction.java:273)
	at clojure.lang.LockingTransaction.runInTransaction(LockingTransaction.java:229)
	at hara.state.ova$ova.invokeStatic(ova.clj:206)
	at hara.state.ova$ova.invoke(ova.clj:193)
	at hara.io.scheduler.array$seed_fn$fn__3659.invoke(array.clj:49)
	at hara.core.component$system$fn__633.invoke(component.clj:599)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8437.invokeStatic(core.clj:6845)
	at clojure.core$fn__8437.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at hara.core.component$system.invokeStatic(component.clj:593)
	at hara.core.component$system.invoke(component.clj:537)
	at hara.io.scheduler$scheduler.invokeStatic(scheduler.clj:40)
	at hara.io.scheduler$scheduler.invoke(scheduler.clj:22)
	at hara.io.scheduler$scheduler.invokeStatic(scheduler.clj:38)
	at hara.io.scheduler$scheduler.invoke(scheduler.clj:22)
	at hara.io.scheduler$scheduler.invokeStatic(scheduler.clj:37)
	at hara.io.scheduler$scheduler.invoke(scheduler.clj:22)
	at hara_test.core__init.load(Unknown Source)
	at hara_test.core__init.<clinit>(Unknown Source)
	... 14 more
```

I hope you can help me solve this. Let me know if you need any additional information.

**Comment by zcaudate** [comment]
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'hara.state/empty

this line is the problem. let me take a look.

**Comment by zcaudate** [comment]
okay... this is by no means solving the issue but as a workaround, can you put this file: https://gist.github.com/zcaudate/72b4a4047fabe3c3a18370be3bf6610e into `hara/state/ova.clj` file in your source folder, uberjar it and see if it runs.

The only changes I've made are at L6 and L108 to the original. I'm still not sure why the #'hara.state/empty var is unbound.

**Comment by zcaudate** [comment]
The problem has to do with instantiation. It depends on when the scheduler is defined in the namespace.

This works:

```
(ns scheduler-test.core
  (:require [hara.io.scheduler :refer [scheduler start!]])
  (:gen-class))

(defn -main []
  (let [sch2 (scheduler {:hello {:handler  (fn [t params] (println t))
                                :schedule "/2 * * * * * *"
                                :params {}}}
                       {}
                       {:clock {:type "java.time.Instant"}})]
    (start! sch2)))
```

This will not (throwing the error)

```
(ns scheduler-test.core
  (:require [hara.io.scheduler :refer [scheduler start!]])
  (:gen-class))

(def sch2 (scheduler {:hello {:handler  (fn [t params] (println t))
                              :schedule "/2 * * * * * *"
                              :params {}}}
                     {}
                     {:clock {:type "java.time.Instant"}}))

(defn -main []
  (start! sch2))
```

the most basic example that fails uberjar is this:

```
(ns scheduler-test.core
  (:require [hara.state :as state])
  (:gen-class))

;; when this is uncommented, uberjar will fail
;; (state/set (atom []) 1)

(defn -main []
  (state/empty (atom []) 1))
```

I'm not sure how to get around this.

**Comment by Eschon** [comment]
I just tried your working example and it still fails for me somehow but the first exception is gone now. Here's the new error message I get:

```
Exception in thread "main" java.lang.IllegalStateException: Attempting to call unbound fn: #'hara.state/empty
	at clojure.lang.Var$Unbound.throwArity(Var.java:45)
	at clojure.lang.AFn.invoke(AFn.java:32)
	at hara.state.ova.Ova._set_state(ova.clj:107)
	at hara.state.base.common$set.invokeStatic(common.clj:90)
	at hara.state.base.common$set.invoke(common.clj:81)
	at hara.state.base.common$set.invokeStatic(common.clj:88)
	at hara.state.base.common$set.invoke(common.clj:81)
	at hara.state.ova$ova$fn__1838.invoke(ova.clj:207)
	at clojure.lang.AFn.call(AFn.java:18)
	at clojure.lang.LockingTransaction.run(LockingTransaction.java:273)
	at clojure.lang.LockingTransaction.runInTransaction(LockingTransaction.java:229)
	at hara.state.ova$ova.invokeStatic(ova.clj:206)
	at hara.state.ova$ova.invoke(ova.clj:193)
	at hara.io.scheduler.array$seed_fn$fn__3659.invoke(array.clj:49)
	at hara.core.component$system$fn__633.invoke(component.clj:599)
	at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
	at clojure.core$fn__8437.invokeStatic(core.clj:6845)
	at clojure.core$fn__8437.invoke(core.clj:6830)
	at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
	at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
	at clojure.core$reduce_kv.invoke(core.clj:6847)
	at hara.core.component$system.invokeStatic(component.clj:593)
	at hara.core.component$system.invoke(component.clj:537)
	at hara.io.scheduler$scheduler.invokeStatic(scheduler.clj:40)
	at hara.io.scheduler$scheduler.invoke(scheduler.clj:22)
	at hara_test.core$_main.invokeStatic(core.clj:6)
	at hara_test.core$_main.invoke(core.clj:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at hara_test.core.main(Unknown Source)
```

I tried it with both with and without the file from your previous comment but it doesn't seem to change anything.

**Comment by zcaudate** [comment]
Can you push up the repo to github?

**Comment by zcaudate** [comment]
Can you confirm that this does not work:


(ns scheduler-test.core
  (:require [hara.io.scheduler :refer [scheduler start!]])
  (:gen-class))

(def sch2 (scheduler {:hello {:handler  (fn [t params] (println t))
                              :schedule "/2 * * * * * *"
                              :params {}}}
                     {}
                     {:clock {:type "java.time.Instant"}}))

(defn -main []
  (start! sch2))

**Comment by Eschon** [comment]
Yes, that code gives me the error that I reported in the beginning.

If it helps I can create a repository with the code from your previous example that should work so that you can check it out

**Comment by zcaudate** [comment]
that'll be great. the previous code works for me when it is uberjared.

**Comment by zcaudate** [comment]
Sorry. Can you check if this code works. It's fine for me when uberjarred.

```
(ns scheduler-test.core
  (:require [hara.io.scheduler :refer [scheduler start!]])
  (:gen-class))

(defn -main []
  (let [sch2 (scheduler {:hello {:handler  (fn [t params] (println t))
                                :schedule "/2 * * * * * *"
                                :params {}}}
                       {}
                       {:clock {:type "java.time.Instant"}})]
    (start! sch2)))
```

**Comment by Eschon** [comment]
Yes that is the code that gave me the error I mentioned before. I don't know if it is relevant but I use Leiningen 2.9.1 and I tried it with both Java 8 and 11

**Comment by zcaudate** [comment]
that's strange. I have the same versions using clojure 10. can you put your example code up on github? I'll try it out.

**Comment by Eschon** [comment]
I pushed it here:
https://github.com/Eschon/hara-scheduler-test

I hope it's not something really stupid and obvious 😅

**Comment by Eschon** [comment]
Your pull request fixed the problem for the test project but somehow I can't get my actual project to work. I still get the same error I posted above.

I can't share the code for the project so I'll keep investigating and let you know if I find anything else

**Comment by zcaudate** [comment]
Thanks @Eschon. I think I know what the problem is. I'll try and push a newer version soon.

**Comment by zcaudate** [comment]
3.0.7 is up and it seems to work with the example. let me know if this solves it for you.

**Comment by Eschon** [comment]
It works without problems now. Thank you so much for your help!  
I was looking also looking at alternative libraries but I really love how easy and concise yours is.

**Comment by zcaudate** [comment]
awesome.
